get '/schedules', to: 'schedules#index', as: 'schedules'
get '/schedules/new', to: 'schedules#new'
post '/schedules/create', to: 'schedules#create'
post '/schedules/delete', to: 'schedules#delete'
post '/schedules/edit', to: 'schedules#edit'
